config/routes.rb
Rails.application.routes.draw do
  root 'departments#index'

  
  resources :departments do
    resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :update, :edit, :destroy]

  def index
    @departments = Department.all
  end

  def show
  end

  def new
    @department = Department.new
    render partial: "form"
  end

  def create
    @department = Department.create(department_params)
    if @department.save
      redirect_to root_path
    else
      rend :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @department.update(department_params)
      redirect_to @department
    else
      render :edit
    end
  end

  def destroy
    @department.destroy
    redirect_to root_path
  end

  private
    def department_params
      params.require(:department).permit(:name)
    end

    def set_department
      @department = Department.find(params[:id])
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_department
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = @department.items
  end

  def show
  end

  def new
    @item = @department.items.new
    render partial: "form"
  end

  def create
    @item = @department.items.create(item_params)
    if @item.save
      redirect_to [@department, @item]
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @item.update(item_params)
      redirect_to [@department, @item]
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to department_items_path
  end

  private
    def set_department
      @department = Department.find(params[:department_id])
    end

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :price)
    end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/departments/_form.html.erb
<%= @department.id ? 'Edit Department': 'Create Department' %>
<br />
<br />
<%= form_for @department do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>

  <br />
  <br />
  <%= f.submit %>
<% end %> 

app/views/departments/edit.html.erb
<h1>Departments#edit</h1>
<p>Find me in app/views/departments/edit.html.erb</p>

app/views/departments/index.html.erb
<h1>Department Store</h1>

<%= link_to 'Create New Department', new_department_path %>

<br />
<br />

<% @departments.each do |department| %>
  <%= link_to department.name, department %>
<% end %>

app/views/departments/new.html.erb
<h1>Departments#new</h1>
<p>Find me in app/views/departments/new.html.erb</p>

app/views/departments/show.html.erb
<h1><%= @department.name %></h1>

<%= link_to 'View Items', department_items_path(@department) %>

<br />
<br />
<%= link_to 'Edit Department', edit_department_path(@department) %>

<br />
<br />
<%= link_to 'Delete Department', @department, method: :delete %>

<br />
<br />
<%= link_to 'Back to Department Store', root_path %>

app/views/items/_form.html.erb
<%= @item.id ? "Edit Item" : "Create Item" %>
<br />
<br />
<%= form_for [@department, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <br />
  <br />
  
  <%= f.label :price %>
  <%= f.number_field :price %>

  <br />
  <br />

  <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h1>Items</h1>

<%= link_to 'Create a new item', new_department_item_path(@department) %>

<br />
<br />

<%= link_to 'Back to Department', department_path(@department) %>

<br />
<br />

<%= @items.each do |item| %>
  <%= link_to item.name, [@department, item] %>

<% end %>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1><%= @department.name %> - <%= @item.name %></h1>

<h2>Price: $<%= @item.price %></h2>


<br />
<br />
<%= link_to 'Edit Item', edit_department_item_path([@department, @item])  %>

<br />
<br />
<%= link_to 'Delete Item', [@department, @item], method: :delete %>

<br />
<br />
<%= link_to 'Back to Items', department_items_path(@department) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>